WIP: working POC
ems-project/EMSCommonBundle pull request #186
Opened 2020-12-14 16:41 UTC by laurensmertens

|Q              |A  |
|---------------|---|
|Bug fix?       |No|
|New feature?   |Yes|	
|BC breaks?     |No|	
|Deprecations?  |No|	
|Fixed tickets  |No|	

Working proof of concept for zipping multiple files.

2020-12-15 10:43 UTC, Davidmattei requested changes

2020-12-15 10:43 UTC, Davidmattei commented on src/Storage/Processor/Config.php
> +
Use a file collection object so not all content is in memory

2020-12-15 10:43 UTC, Davidmattei commented on src/Storage/Processor/Zip.php
> +        $zip = new \ZipArchive();
Use https://github.com/maennchen/ZipStream-PHP
And check $zip->addFileFromStream('goodbye.txt', $fp);

2020-12-18 12:07 UTC, Davidmattei approved these changes

2020-12-21 10:08 UTC, theus77 approved these changes
For later

- stream the response
- register the file processor with a compiler

2020-12-25 14:50 UTC, merged