Spreadsheet export service
ems-project/EMSCommonBundle pull request #229
Opened 2021-02-19 11:55 UTC by laurensmertens

|Q              |A  |
|---------------|---|
|Bug fix?       |No|
|New feature?   |Yes|	
|BC breaks?     |No|	
|Deprecations?  |No|	
|Fixed tickets  |No|	

Service to allow spreadsheet exports based on JSON.

2021-02-19 19:00 UTC, theus77 commented on src/Common/SpreadsheetGeneratorService.php
> +        $resolver->resolve($config);
I would isolate it in a function with the right return hint

2021-02-20 10:42 UTC, laurensmertens commented on tests/Unit/Common/SpreadsheetGeneratorTest.php
> +    private $spreadSheetGenerator;
It's not yet available in PHP 7.2

2021-02-21 22:22 UTC, theus77 commented on tests/Unit/Common/SpreadsheetGeneratorTest.php
> +    private $spreadSheetGenerator;
Ok. I'll upgrade it

2021-02-21 22:26 UTC, theus77 approved these changes

2021-02-21 22:27 UTC, theus77 commented
I let David approve and merge it

2021-02-22 08:36 UTC, Davidmattei commented on src/Common/SpreadsheetGeneratorService.php
> +        exit;
+1

2021-02-26 08:29 UTC, Davidmattei requested changes

2021-02-27 09:14 UTC, merged