fix: s3 seekable
ems-project/EMSCommonBundle pull request #431
Opened 2022-07-13 12:54 UTC by theus77

|Q              |A  |
|---------------|---|
|Bug fix?       |y|
|New feature?   |n|	
|BC breaks?     |n|	
|Deprecations?  |n|	
|Fixed tickets  |n|

2022-07-13 13:00 UTC, Davidmattei requested changes

2022-07-13 21:47 UTC, theus77 commented on src/Storage/Service/AbstractUrlStorage.php
> +        }
I tried, but phpstan complains that the getContext fonction can returns a null. So I had 2 options this one, or add an exception in the baseline.

2022-07-14 07:26 UTC, Davidmattei commented on src/Storage/Service/AbstractUrlStorage.php
> +        }
Okay then it's okay

2022-07-14 07:26 UTC, Davidmattei approved these changes

2022-07-14 07:28 UTC, merged